---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mavenwebappdeployment
spec:
    replicas: 2
    strategy:
        type: RollingUpdate
    selector:
        matchLabels:
            app: mavenwebapp
    template:
        metadata:
            name: mavenwebapppod
            labels:
                app: mavenwebapp
        spec:
            containers:
                - name: mavenwebappcontainer
                  image: rayhubli/maven_app:${TAG}
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: mavenwebappsvc
spec:
    type: NodePort
    selector:
        app: mavenwebapp
    ports:
        - port: 80
          targetPort: 8080
          nodePort: 32000
...
